version: '3.8'

services:
  graphql:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - mongo
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file: mongo.env
    environment:
      MONGO_INITDB_DATABASE: finance_tracker
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # initialize database
      - ./mongo-data:/data/db # preserve data
